#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DeviceSampleAPI.Resource", IsApplication=true)]

namespace DeviceSampleAPI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001d
			public const int action_reset = 2131230749;
			
			// aapt resource value: 0x7f080008
			public const int btnBg = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int btnGps = 2131230729;
			
			// aapt resource value: 0x7f080010
			public const int btnLed = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int btnLedEnable = 2131230737;
			
			// aapt resource value: 0x7f08000a
			public const int btnLocationSettings = 2131230730;
			
			// aapt resource value: 0x7f08000f
			public const int btnNFCSettings = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int btnNfc = 2131230733;
			
			// aapt resource value: 0x7f08001b
			public const int btnTLock = 2131230747;
			
			// aapt resource value: 0x7f080019
			public const int button1 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int button2 = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int button3 = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int button4 = 2131230743;
			
			// aapt resource value: 0x7f08000b
			public const int gpsStatus = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int layInfo = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int listMainActivities = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int listReset = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int listSuspendTimeout = 2131230741;
			
			// aapt resource value: 0x7f080005
			public const int listThreshCrit = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int listThreshLow = 2131230723;
			
			// aapt resource value: 0x7f080016
			public const int listWakeupSource = 2131230742;
			
			// aapt resource value: 0x7f08001c
			public const int menu_reset = 2131230748;
			
			// aapt resource value: 0x7f08000e
			public const int nfcStatus = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int textMainActivities = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int textView1 = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int textView2 = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int txtInfo = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int txtPower = 2131230721;
			
			// aapt resource value: 0x7f080013
			public const int txtSleep = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int txtSleepSelection = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_battery = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_location = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_nfc = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_notification = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_reset = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_sleep = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_touch = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int reset = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int action_reset = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int action_settings = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int btnTouch = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int hint = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int title_activity_battery = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int title_activity_info = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int title_activity_location = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int title_activity_nfc = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int title_activity_notification = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int title_activity_reset = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int title_activity_sleep = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int title_activity_touch = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int txt_hint_battery = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int txt_hint_info = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int txt_hint_location = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int txt_hint_nfc = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int txt_hint_notification = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int txt_hint_reset = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int txt_hint_sleep = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int txt_hint_start = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int txt_thresh_crit = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int txt_thresh_low = 2131034133;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
