#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DeviceSampleAPI.Resource", IsApplication=true)]

namespace DeviceSampleAPI
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F010000
			public const int activity_horizontal_margin = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int activity_vertical_margin = 2130771969;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7F020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int action_reset = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnBg = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int btnGps = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int btnLed = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int btnLedEnable = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int btnLocationSettings = 2130903045;
			
			// aapt resource value: 0x7F030007
			public const int btnNfc = 2130903047;
			
			// aapt resource value: 0x7F030006
			public const int btnNFCSettings = 2130903046;
			
			// aapt resource value: 0x7F030008
			public const int btnTLock = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int button1 = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int button2 = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int button3 = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int button4 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int gpsStatus = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int layInfo = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int listMainActivities = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int listReset = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int listSuspendTimeout = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int listThreshCrit = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int listThreshLow = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int listWakeupSource = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int menu_reset = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int nfcStatus = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int textMainActivities = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int textView1 = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int textView2 = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int txtInfo = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int txtPower = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int txtSleep = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int txtSleepSelection = 2130903069;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_battery = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_info = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int activity_location = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int activity_main = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int activity_nfc = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int activity_notification = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int activity_reset = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int activity_sleep = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int activity_touch = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int reset = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060001
			public const int action_reset = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int action_settings = 2131099650;
			
			// aapt resource value: 0x7F060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7F060003
			public const int app_name = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int btnTouch = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int hint = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int title_activity_battery = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int title_activity_info = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int title_activity_location = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int title_activity_nfc = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int title_activity_notification = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int title_activity_reset = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int title_activity_sleep = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int title_activity_touch = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int txt_hint_battery = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int txt_hint_info = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int txt_hint_location = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int txt_hint_nfc = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int txt_hint_notification = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int txt_hint_reset = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int txt_hint_sleep = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int txt_hint_start = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int txt_thresh_crit = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int txt_thresh_low = 2131099671;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
