#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JoyaTouchCradleSampleAPI.Resource", IsApplication=true)]

namespace JoyaTouchCradleSampleAPI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int buttonClearCustom = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int buttonReadConfig = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int buttonReadCustom = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int buttonWriteConfig = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int buttonWriteCustom = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int configValuesGrid = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int customValuesText = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int editTextConfigAreaGridCell = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int item_refresh = 2131165200;
			
			// aapt resource value: 0x7f070001
			public const int layoutReadWriteConfigValues = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int layoutReadWriteCustomValues = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int listLedActions = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int listLockActions = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int listMainActivities = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int textDeviceInCradle = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int textMainActivities = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int textState = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_cradle_config_area = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_cradle_custom_area = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_cradle_led = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_cradle_lock = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_cradle_state_info = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int config_area_grid_cell = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int cradle_state_info_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int action_settings = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050010
			public const int clear = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int device_in_cradle = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int device_not_in_cradle = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int get_cradle_state_failed = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int read = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int refresh = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int start = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int title_activity_config_area = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int title_activity_custom_area = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int title_activity_get_cradle_state = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int title_activity_led = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int title_activity_lock = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int write = 2131034127;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
