#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JoyaTouchCradleSampleAPI.Resource", IsApplication=true)]

namespace JoyaTouchCradleSampleAPI
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F010000
			public const int activity_horizontal_margin = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int activity_vertical_margin = 2130771969;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int buttonClearCustom = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int buttonReadConfig = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int buttonReadCustom = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int buttonWriteConfig = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int buttonWriteCustom = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int configValuesGrid = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int customValuesText = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int editTextConfigAreaGridCell = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int item_refresh = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int layoutReadWriteConfigValues = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int layoutReadWriteCustomValues = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int listLedActions = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int listLockActions = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int listMainActivities = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int textDeviceInCradle = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int textMainActivities = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int textState = 2130903056;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_cradle_config_area = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_cradle_custom_area = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int activity_cradle_led = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int activity_cradle_lock = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int activity_cradle_state_info = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int config_area_grid_cell = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int Main = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int cradle_state_info_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060002
			public const int action_settings = 2131099650;
			
			// aapt resource value: 0x7F060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7F060003
			public const int app_name = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int clear = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int device_in_cradle = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int device_not_in_cradle = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int get_cradle_state_failed = 2131099655;
			
			// aapt resource value: 0x7F060001
			public const int Hello = 2131099649;
			
			// aapt resource value: 0x7F060008
			public const int read = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int refresh = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int start = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int title_activity_config_area = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int title_activity_custom_area = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int title_activity_get_cradle_state = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int title_activity_led = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int title_activity_lock = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int write = 2131099664;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
