#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DecodeIntent.Resource", IsApplication=true)]

namespace DecodeIntent
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F010000
			public const int activity_horizontal_margin = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int activity_vertical_margin = 2130771969;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int myicon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int radioBroadcast = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int radioGroup = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int radioStartActivity = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int startBtn = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int stoptBtn = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int textResult = 2130903045;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_intent_start = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_started_from_broadcast = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int intent_wedge_sample = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int Icon = 2131034112;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int activity_result = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int hello = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int initial_hint = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int intent_start_activity = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int intent_wedge_sample = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int radioActivity_string = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int radioBroadcast_string = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int radioService_string = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int startBTN = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int stopBTN = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int title_activity_intent_start = 2131099659;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
